### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by SzotsGabor** [likeawizard/tofiks#48]
Hi Arturs,

I guess that is your name although your engine (v1.2) displays Aturs.

Some problems and requests (I use the avx2 version):

1. Maybe including version in the file name could avoid accidents (mistaking one version with another one).
2. 'go depth 10' analyzes only up to depth 5.
3. 'go perft 10' does not do anything.
4.  After the above a new 'go' command makes the engine quit.

Gabor Szots
CCRL testing group

Edit: I think I understand problem (3) now, 'go perft 5', 'go perft 6' and 'go perft 7' are OK, obviously depth 10 takes a lot of time. Probably that causes problem (4).

**Comment by likeawizard** [comment]
@SzotsGabor I will investigate. My UCI implementation has been good enough for most cases but I know there are issues there. I need to create better implementation for the `go` command it now only treats `go` well with time constraints which is the most common use case. So `go depth 10` is like `go movetime 0 depth 10`.

For a fact I know that some uci commands can make it crash, where the proper way of doing it would ignoring them. Usually this should not happen.

As far as the version - it reports the version via `uci` command:
```
id name Tofiks v1.2.0
id author Aturs Priede
option name Ponder type check default false
option name Hash type spin default 64 min 1 max 256
option name Clear Hash type button
option name Move Overhead type spin default 0 min 0 max 1000
option name OwnBook type check default false
```

I guess your question is regarding the binaries included in the releases showing the version in the filename?

Arturs.

**Comment by SzotsGabor** [comment]
> 
> ```
> id name Tofiks v1.2.0
> id author Aturs Priede
> option name Ponder type check default false
> option name Hash type spin default 64 min 1 max 256
> option name Clear Hash type button
> option name Move Overhead type spin default 0 min 0 max 1000
> option name OwnBook type check default false
> ```
> 
> I guess your question is regarding the binaries included in the releases showing the version in the filename?
> 
> Arturs.

Yes. I meant an exe name such as tofiks1.2-avx2.exe (instead of tofiks-avx2.exe) would prevent mistaking versions.

And, may I ask you, are you from Lithuania?

**Comment by likeawizard** [comment]
That's a good suggestion. I will do that.
Close - Latvia.

**Comment by likeawizard** [comment]
@SzotsGabor I updated the release binary names with the version.

I saw you are with CCRL. I always wondered how could I get my engine listed on the rankings. Are there any minimum requirements?

**Comment by SzotsGabor** [comment]
> @SzotsGabor I updated the release binary names with the version.
> 
> I saw you are with CCRL. I always wondered how could I get my engine listed on the rankings. Are there any minimum requirements?

The most important requirement is that we are aware of your engine. For example, I have learned about your engine by a post made at the Talkchess forum, https://talkchess.com/forum3/viewtopic.php?f=2&t=82263&sid=53659627ab20a1f3d5e88227c5f312ba&start=80
Otherwise not much. Basic time control capabilities are recommended, such as x moves in y minutes or x minutes base time + y seconds increment. We use the former for the 40/15 list and the latter for the blitz list. I myself currently use 85 s + 1s, calibrated based upon my computer's speed.
What we test is entirely at our discretion. We may skip versions, e.g. owing to lack of resources (we have many engines to test, as you can see).

Anyway, I am just finishing a tournament and will have a free core so I'm just going to start a gauntlet using Tofiks.
